version: "3"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "user_service_api"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    command: ["postgres", "-c", "log_statement=all"]
