version: "3"

volumes:
  postgres_volume:


services:
  postgres:
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_DB: "user_service_api"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./configs/postgres/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54321:5432"
